library(dplyr)
rdata <- read.csv("P220402.csv")
str(rdata)
data <- rdata %>% mutate(pos=(num_loves + num_wows)) %>% mutate(pos_ratio = pos/(num_reactions))
str(data)
#result <- data %>% filter(pos>0.4 & pos<0.5)
result <- data %>% filter(pos_ratio>0.4 & pos_ratio<0.5)
nrow(result)
print(nrow(result))
